# Generated by Django 3.1.2 on 2020-10-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='bg_color',
            field=models.CharField(blank=True, help_text='Enter the background color of the board', max_length=15, null=True),
        ),
    ]
