# Generated by Django 3.1.2 on 2020-10-06 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_boards_bg_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='board',
        ),
        migrations.AddField(
            model_name='columns',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.boards'),
        ),
    ]
