# Generated by Django 3.1.2 on 2020-10-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boards',
            options={'verbose_name': 'Доска', 'verbose_name_plural': 'Доски'},
        ),
        migrations.AlterModelOptions(
            name='cards',
            options={'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterModelOptions(
            name='columns',
            options={'verbose_name': 'Колонка', 'verbose_name_plural': 'Колонки'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
