# Generated by Django 3.1.2 on 2020-10-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20201006_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boards',
            options={'ordering': ['id'], 'verbose_name': 'Доска', 'verbose_name_plural': 'Доски'},
        ),
        migrations.AlterModelOptions(
            name='cards',
            options={'ordering': ['id'], 'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
    ]
